      <div  id="mpiifooter" class="col-md-12">
        <div class="col-md-12 column">
          <ul class="list-unstyled pull-right">
            <li><span class="pull-right">Copyright 2021 by <a href="//www.mpi-inf.mpg.de/">Max Planck Institute for Informatics</a></span></li>
            <li><span class="pull-right"><a href="//imprint.mpi-klsb.mpg.de/inf/people/kteotia">Imprint / Impressum</a>&nbsp;|&nbsp;<a href="//data-protection.mpi-klsb.mpg.de/inf/people/kteotia">Data Protection / Datenschutzhinweis</a></span></li>
          </ul>
        </div>
      </div>
